name: Node pipeline with Inputs

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: Select the environment
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
      port:
        description: Select the port
        required: true
        default: "8080"
      

jobs:
  node:
    runs-on: ["wsl-linux"]
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install packages
        run: npm install

      - name: Run application
        run: |
          node server.js ${{ github.event.inputs.environment }} &
          sleep 5
          curl http://localhost:${{ github.event.inputs.port }}
          curl http://localhost:${{ github.event.inputs.port }}/health
          pkill -f "node server.js ${{ github.event.inputs.environment }}"
